"""Initial migration

Revision ID: 3f6741e8dc8d
Revises: 
Create Date: 2020-01-11 19:16:41.362890

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3f6741e8dc8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titel', sa.String(length=100), nullable=False),
                    sa.Column('eingereicht_von', sa.String(length=100), nullable=False),
                    sa.Column('eingereicht_am', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('frist', sa.Date(), nullable=True),
                    sa.Column('beschreibung', sa.Text(), nullable=True),
                    sa.Column('abstimmungsfragen', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_top_eingereicht_von'), 'top', ['eingereicht_von'], unique=False)
    op.create_index(op.f('ix_top_frist'), 'top', ['frist'], unique=False)
    op.create_index(op.f('ix_top_titel'), 'top', ['titel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_titel'), table_name='top')
    op.drop_index(op.f('ix_top_frist'), table_name='top')
    op.drop_index(op.f('ix_top_eingereicht_von'), table_name='top')
    op.drop_table('top')
    # ### end Alembic commands ###
